name: Feature request
description: A issue used to request new developments.
labels:
  - enhancement
type: feature
body:
  - type: textarea
    attributes:
      label: Feature
      description: Describe the new development that you need.
    validations:
      required: true
  - type: textarea
    attributes:
      value: |
          - [ ] Task 1
          - [ ] Task 2
      label: Tasks
      description: A to do list with steps to show progress.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: true
