name: New Community 
description: Add community information 
projects:
  - UAIBIT/1
labels:
  - community
type: task
body:
  - type: textarea
    attributes:
      label: Tasks
      description: task list what should be done in community to proper register on our auxiliary systems.
      value: |
          - [ ] Create logo
          - [ ] Create github org
          - [ ] Create repo CBTC
            - [ ] Write permission on Workflow
          - [ ] Create PBTC
          - [ ] Create Files
          - [ ] Add at least one merchant on BTC map in region
          - [ ] Create Instagram 
          - [ ] Create lightning address
          - [ ] Create Whatsapp group in UAIBIT
          - [ ] Add channel on our discord
          - [ ] Submit community on BTC map under UAIBIT organization 
          
    validations:
      required: true
  - type: textarea
    attributes:
      label: Community info
      description: Describe the community relevant info to register on our auxiliary systems.
      value: |
       Select Location:  
       Community Name:  
       Icon URL:  
       Lightning Tips:  
       Social Links:  
       Public Contact:  
       Notes:  
       NOTREMOVETHISPLEASE
       {\"OSM_ID\": ,
       \"AREA_TYPE\":\"\",
       \"CONTINENT\":\"\",
       \"ICON\":\"\",
       \"NAME\":\"\",
       \"POPULATION\":,
       \"POPULATION_DATE\":\"\",
       \"CONTACT\":[\"\"]}
    validations:
      required: true
