name: New voluntary
description: Create a report to help us improve
labels:
  - volunteer
projects:
  - UAIBIT/1
type: task
body:
  - type: textarea
    attributes:
      label: Volunteer
      description: Describe the volunteer personal and carrier information.
    validations:
      required: true
